<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <RollForward>Major</RollForward>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AAXClean.Codecs.Test</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../AAXClean.Codecs/AAXClean.Codecs.csproj" />
  </ItemGroup>
</Project>
